// Contamination control.
//
// THE PROBLEM THIS SOLVES: scholarship_essays/ holds 20 essays that read like Colin because they
// were generated by an LLM conditioned on voice_profile.md. Every one carries exactly two
// `"by": "draft"` revisions and zero `"by": "colin"`. If any of that text reaches the corpus, the
// exemplar bank, or the stylometric baseline, then every downstream result measures how well the
// system reproduces an LLM's impression of Colin — and it would look like success.
//
// A convention ("don't use those") cannot enforce this, because contamination arrives sideways:
// via an Obsidian copy, a pasted draft in a chat transcript, a quoted paragraph in a memo. So the
// guard is textual, not path-based: any record sharing an 8-gram with a known essay is rejected
// no matter where it came from. quarantine.test.ts fails the suite on violation.

import { readdirSync, existsSync, readFileSync } from "fs";
import { join } from "path";
import type { CorpusRecord } from "./schema.ts";

export const ESSAYS_DIR = join(import.meta.dir, "..", "scholarship_essays");

/** Path globs whose text may never enter the corpus. */
export const QUARANTINED_PATHS = ["scholarship_essays/"];

/** Shingle size for the textual guard. 8 words is long enough that collisions are meaningful. */
export const NGRAM = 8;

function normTokens(s: string): string[] {
  return (s.toLowerCase().match(/[a-z0-9']+/g) || []);
}

export function ngrams(text: string, n = NGRAM): Set<string> {
  const t = normTokens(text);
  const out = new Set<string>();
  for (let i = 0; i + n <= t.length; i++) out.add(t.slice(i, i + n).join(" "));
  return out;
}

let cache: Set<string> | null = null;

/** Every 8-gram appearing in any generated essay. Built once per process. */
export function contaminatedNgrams(): Set<string> {
  if (cache) return cache;
  const all = new Set<string>();
  if (existsSync(ESSAYS_DIR)) {
    for (const d of readdirSync(ESSAYS_DIR, { withFileTypes: true })) {
      if (!d.isDirectory()) continue;
      const p = join(ESSAYS_DIR, d.name, "essay.md");
      if (!existsSync(p)) continue;
      for (const g of ngrams(readFileSync(p, "utf8"))) all.add(g);
    }
  }
  cache = all;
  return all;
}

export interface ContaminationHit {
  contaminated: boolean;
  reason?: string;
  sharedNgram?: string;
}

/**
 * Is this text contaminated by generated-essay material?
 * Checks the source path first (cheap), then shared 8-grams (the real guard).
 */
export function checkContamination(sourceId: string, text: string): ContaminationHit {
  for (const p of QUARANTINED_PATHS) {
    if (sourceId.includes(p)) return { contaminated: true, reason: `sourceId under ${p}` };
  }
  const bad = contaminatedNgrams();
  if (bad.size === 0) return { contaminated: false };
  for (const g of ngrams(text)) {
    if (bad.has(g)) {
      return { contaminated: true, reason: `shares an ${NGRAM}-gram with a generated essay`, sharedNgram: g };
    }
  }
  return { contaminated: false };
}

/** Throws if the record is contaminated. Call at every boundary that admits text to the corpus. */
export function assertNotContaminated(record: Pick<CorpusRecord, "sourceId" | "text">): void {
  const hit = checkContamination(record.sourceId, record.text);
  if (hit.contaminated) {
    throw new Error(
      `Contaminated record refused (${hit.reason})` +
        (hit.sharedNgram ? `: "${hit.sharedNgram}"` : "") +
        `\n  sourceId: ${record.sourceId}`,
    );
  }
}
