// Bundles the hand-written essays + form triage into a client module the dashboard can import.
// Reads scholarship_essays/{slug}/{essay.md, metadata.json} → writes src/data/essays.js as
// APPLY_KITS keyed by slug. The dashboard matches a scholarship to its kit by slugifying the name.
//
// Essays are Colin's own words (no PII) so bundling them to the client is fine; contact PII stays
// out (it lives only in applicant.local.json, server-side). Re-run after editing essays or re-probing.
//
// Usage: bun scout/emit-essays.ts

import { join } from "path";
import { readdirSync, existsSync } from "fs";

const ESSAYS_DIR = join(import.meta.dir, "..", "scholarship_essays");
const OUT = join(import.meta.dir, "..", "src", "data", "essays.js");

// Strip a leading markdown H1 ("# Title") — committees get the prose, not our filename heading.
const stripH1 = (md: string) => md.replace(/^\s*#\s+.*\r?\n+/, "").trim();

async function main() {
  const slugs = readdirSync(ESSAYS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(join(ESSAYS_DIR, d.name, "essay.md")))
    .map((d) => d.name)
    .sort();

  const kits: Record<string, unknown> = {};
  for (const slug of slugs) {
    const essay = stripH1(await Bun.file(join(ESSAYS_DIR, slug, "essay.md")).text());
    let md: any = {};
    const metaPath = join(ESSAYS_DIR, slug, "metadata.json");
    if (existsSync(metaPath)) md = await Bun.file(metaPath).json();
    const fm = md.formMeta ?? null;
    kits[slug] = {
      name: md.name ?? slug,
      org: md.org ?? null,
      amount: md.amount ?? null,
      deadline: md.deadline ?? null,
      url: md.url ?? null,
      applyUrl: fm?.applyUrl ?? null,
      route: fm?.route ?? null,
      applicationFee: fm?.applicationFee ?? false,
      loginRequired: fm?.loginRequired ?? false,
      essayRequired: fm?.essayRequired ?? false,
      essayWordLimit: fm?.essayPrompts?.[0]?.wordLimit ?? null,
      platform: fm?.platform ?? null,
      angle: md.angle_used ?? null,
      match: md.match_pct ?? null,
      wordCount: essay.split(/\s+/).filter(Boolean).length,
      essay,
    };
  }

  const banner = "// AUTO-GENERATED by scout/emit-essays.ts — do not edit by hand. Re-run after editing essays or probing.\n";
  const body =
    `export const APPLY_KITS = ${JSON.stringify(kits, null, 2)};\n\n` +
    `export const APPLY_KITS_GENERATED_AT = ${JSON.stringify(new Date().toISOString())};\n`;
  await Bun.write(OUT, banner + body);
  console.log(`Wrote ${slugs.length} apply kits → ${OUT}`);
}

main().catch((e) => { console.error(`emit-essays failed: ${e instanceof Error ? e.message : e}`); process.exit(1); });
