// Bundle the open checkpoint queue into a module the static dashboard can import.
//
// Same mechanism scout/scout.ts --emit-app already uses for src/data/scoutFound.js, so the static
// Vite build keeps working with no backend. When server.ts is running locally the app prefers the
// live /api/queue endpoint and falls back to this file.
//
// NO PII AND NO SECRETS. The queue carries the question, the type, evidence REFERENCES (paths and
// URLs), and confidence numbers — never a field value, never a credential.
//
// Usage: bun state/emit-queue.ts

import { writeFileSync } from "fs";
import { join } from "path";
import { readAll } from "./log";
import { fold } from "./rebuild";
import { CHECKPOINTS } from "./checkpoints.js";

const OUT = join(import.meta.dir, "..", "src", "data", "interventions.js");

/** Values are stripped; only references and metadata survive into the bundle. */
function safeContext(ctx: Record<string, unknown>): Record<string, unknown> {
  const allow = new Set(["slug", "name", "fieldLabel", "path", "reason", "situation", "url", "portal", "competingRules", "reasons", "batchSize", "patterns", "listing_url"]);
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(ctx ?? {})) if (allow.has(k)) out[k] = v;
  return out;
}

export function buildQueue() {
  const p = fold(readAll());
  return Object.values<any>(p.checkpoints)
    .map((cp) => ({
      checkpointId: cp.checkpointId,
      applicationId: cp.applicationId,
      type: cp.type,
      status: cp.status,
      createdAt: cp.createdAt,
      blocking: cp.blocking,
      question: cp.question,
      rationale: CHECKPOINTS[cp.type]?.rationale ?? null,
      context: safeContext(cp.context),
      evidenceRefs: cp.evidenceRefs,
      missingEvidence: cp.missingEvidence,
      allowedResolutions: cp.allowedResolutions,
      resolverRoles: cp.resolverRoles,
    }))
    .sort((a, b) => Number(b.blocking) - Number(a.blocking) || a.createdAt.localeCompare(b.createdAt));
}

if (import.meta.main) {
  const queue = buildQueue();
  const banner = "// AUTO-GENERATED by state/emit-queue.ts — do not edit by hand.\n";
  writeFileSync(
    OUT,
    banner +
      `export const INTERVENTIONS = ${JSON.stringify(queue, null, 2)};\n\n` +
      `export const INTERVENTIONS_GENERATED_AT = ${JSON.stringify(new Date().toISOString())};\n`,
    "utf8",
  );
  const blocking = queue.filter((q) => q.blocking).length;
  console.log(`Wrote ${queue.length} open checkpoint(s) (${blocking} blocking) → ${OUT}`);
}
